Dockerfile, deepcell/model_zoo.py, requirements.txt
=> Upgrade base image to 18.08 and tf1.9

.coveragerc, .travis.yml, README.md, deepcell/layers/location.py, deepcell/layers/normalization.py, deepcell/layers/padding.py, deepcell/layers/pooling.py, deepcell/layers/resize.py, deepcell/layers/tensor_product.py, deepcell/model_zoo.py, deepcell/utils/__init__.py, deepcell/utils/testing_utils.py, tests/deepcell/layers/location_test.py, tests/deepcell/layers/normalization_test.py, tests/deepcell/layers/padding_test.py, tests/deepcell/layers/pooling_test.py, tests/deepcell/layers/resize_test.py, tests/deepcell/layers/tensor_product_test.py, tests/deepcell/running_test.py, tests/deepcell/utils/data_utils_test.py, tests/deepcell/utils/transform_utils_test.py
=> Testing for custom layers

deepcell/layers/tensor_product.py, deepcell/model_zoo.py, tests/deepcell/layers/tensor_product_test.py
=> combine TensorProd2D and TensorProd3D into single TensorProduct layer

deepcell/metrics.py, scripts/misc/Model_Metrics.ipynb, tests/deepcell/metrics_test.py
- Remove deprecated functions and their corresponding tests
- Add appropriate references to the code and the notebook
- Add copyright header to code and test files
- Add documentation that elaborates how metrics were chosen and implemented
=> Update metrics code

deepcell/datasets/tracked/hek293.py, deepcell/datasets/tracked/hela_s3.py, deepcell/datasets/tracked/nih_3t3.py, deepcell/image_generators.py, deepcell/tracking.py, deepcell/utils/plot_utils.py, deepcell/utils/tracking_utils.py, tests/deepcell/image_generators_test.py
These changes should help all the tests pass.
=> PEP8 changes for cell_tracking

deepcell/training.py
=> pass `seed` to each flow() call and each get_data() call

deepcell/datasets/__init__.py, deepcell/datasets/mibi.py
=> add MIBI dataset to deepcell.datasets

deepcell/datasets/__init__.py, deepcell/datasets/cytoplasm.py, deepcell/datasets/phase.py, deepcell/datasets/tracked.py, deepcell/utils/data_utils.py, pytest.ini
Made all the changes I mentioned in Slack.  No circular import if you import submodules after defining `Dataset`.
I simply tested `deepcell.datasets.hela_s3.load_data` but it works as expected.
=> Dataset inside deepcell.datasetes, objects not classes

deepcell/running.py, deepcell/running_test.py
Fixes #10
Adds tests for `process_whole_image`
=> Remove deprecated run_model functions in running.py

README.md, deepcell/image_generators.py, deepcell/image_generators_test.py, deepcell/model_zoo/__init__.py, deepcell/model_zoo/maskrcnn.py, deepcell/model_zoo/maskrcnn_test.py, deepcell/utils/__init__.py, deepcell/utils/transform_utils.py, deepcell/utils/transform_utils_test.py, scripts/feature_pyramids/RetinaMask.ipynb, scripts/pixelwise/Interior-Edge Segmentation 2D Fully Convolutional.ipynb, scripts/pixelwise/Interior-Edge Segmentation 2D Sample Based.ipynb, scripts/pixelwise/Interior-Edge Segmentation 3D Fully Convolutional.ipynb, scripts/pixelwise/Interior-Edge Segmentation 3D Sample Based.ipynb
Also added links to the FPN notebooks in the README.  Resolves #191
=> Refactor deepcell transform to pixelwise and MaskRCNN to RetinaMask

deepcell/training.py
=> bugfix: train_data was getting data from datagen_val, not datagen in train_model_conv

deepcell/layers/filter_detections.py, deepcell/layers/filter_detections_test.py
Pass `score_threshold` to `tf.image.non_max_suppression`
=> Bugfix #215

.travis.yml, deepcell/applications/cell_tracking.py, deepcell/applications/fluorescent_cytoplasm_segmentation.py, deepcell/applications/label_detection.py, deepcell/applications/nuclear_segmentation.py, deepcell/applications/phase_segmentation.py, deepcell/applications/scale_detection.py, deepcell/callbacks_test.py, deepcell/datasets/__init__.py, deepcell/image_generators.py, deepcell/layers/filter_detections.py, deepcell/layers/filter_detections_test.py, deepcell/layers/location.py, deepcell/layers/normalization.py, deepcell/layers/pooling.py, deepcell/layers/resize.py, deepcell/layers/retinanet.py, deepcell/layers/tensor_product.py, deepcell/layers/upsample.py, deepcell/model_zoo/maskrcnn.py, deepcell/model_zoo/maskrcnn_test.py, deepcell/utils/backbone_utils.py, deepcell/utils/data_utils.py, requirements.txt
To use TensorFlow version 1.8 or 1.9, please use [release 0.1.0](https://github.com/vanvalenlab/deepcell-tf/releases/tag/0.1.0)
=> Stop support for Tensorflow<1.10.0

deepcell/utils/data_utils.py, deepcell/utils/data_utils_test.py
=> Relabel the output of reshape_matrix to be sequential

deepcell/layers/__init__.py, deepcell/layers/convolutional_recurrent.py, deepcell/layers/convolutional_recurrent_test.py
Added `ConvGRU2D` layer in `convolutional_recurrent.py` and added unit test for it. These unit tests were written in reference to tests for pooling and tensor product layers.
=> Added convolutional recurrent layers and unit tests

deepcell/datasets/phase.py
=> Update all_cell to all_cells in datasets/phase.py

deepcell/datasets/__init__.py
=> HEK293 should download HEK data.

deepcell/applications/cell_tracking.py, deepcell/applications/fluorescent_cytoplasm_segmentation.py, deepcell/applications/label_detection.py, deepcell/applications/nuclear_segmentation.py, deepcell/applications/phase_segmentation.py, deepcell/applications/scale_detection.py, deepcell/image_generators/__init__.py, deepcell/image_generators/fully_convolutional.py, deepcell/image_generators/retinanet.py, deepcell/image_generators/sample.py, deepcell/image_generators/scale.py, deepcell/image_generators/tracking.py, deepcell/metrics.py, deepcell/model_zoo/fpn.py, deepcell/model_zoo/maskrcnn.py, deepcell/model_zoo/retinanet.py, deepcell/utils/data_utils.py, deepcell/utils/retinanet_anchor_utils.py
* Added improved docstrings to `applications`, `image_generators`, `metrics`, `model_zoo`, and `retinanet_anchor_utils`.
* For better compatibility with `sphinx` and to generally improve documentation.
=> Update docstrings for compatibility with sphinx.

deepcell/model_zoo/fpn.py
* Corrected an error in the code to build feature pyramids that resulted in adding layers in the wrong place in the pyramid
* Improves overall accuracy and performance of models using feature pyramids
=> Correct FPN bug with misplaced lines of code

deepcell/applications/cytoplasm_segmentation.py
* Add `deepcell_toolbox.processing.phase_process` as the preprocessing function for the cytoplasm application
* The model was trained using data with this preprocessing function
=> Add preprocessing function to cytoplasm app

README.md
* Fixed spacing in the code block in the README.
* The `-p 8888:8888` is spaced weirdly.
=> Fix spacing in code block in README.

deepcell/applications/application.py, requirements.txt
* Upgrade the `deepcell_toolbox` version requirement to at least `0.4.0`.
* Fixes #369
=> update deepcell-toolbox version to 0.4.0

deepcell/applications/label_detection.py, deepcell/applications/scale_detection.py
* Updated hashes for Scale and Label detection models.
* The current file hashes are wrong and will never get cached.
=> Update hashes for Label and Scale detection models.

setup.py
* Change setup.py version to 0.5.0.
* In preparation for the release of 0.5.0.
=> change version to 0.5.0 in setup.py

README.md
* Fix the badge URL for the readthedocs badge.
* The badge was not working.
=> Fix documentation badge

deepcell/applications/multiplex_segmentation.py
Updated the current application for multiplex models to include the new weights file, model parameters, and preprocessing so that Dave and I can use it for testing models.
=> MultiplexSegmentation update

deepcell/applications/multiplex_segmentation.py
* New weights file for multiplex application
* Going to be sending out link to repo to beta testers this week
=> Updated multiplex application

deepcell/applications/multiplex_segmentation.py
* Changed the hash of the MultiplexSegmentation weights file.
* Prevent the weights file to be hashed.
=> Update MultiplexSegmentation model weights file hash.

deepcell/applications/multiplex_segmentation.py
Updates the default values of post-processing in the applications based on the HPS
Better accuracy for predictions
=> Updated post-processing values

deepcell/applications/multiplex_segmentation.py
Updated the weights file for the multiplex application with newest model
Hopefully this will be the last time time we have to update the applications separately, and once we move this to deepcell-applications they can use the same saved_model file as the consumers.
=> Update multiplex application

setup.py
* Update version to 0.7.0 in setup.py
* Final change for pending release.
=> Bump version to 0.7.0 in setup.py.

deepcell/applications/__init__.py, deepcell/applications/label_detection.py, deepcell/applications/label_detection_test.py, deepcell/applications/multiplex_segmentation.py, deepcell/applications/multiplex_segmentation_test.py, deepcell/applications/nuclear_segmentation.py, deepcell/applications/nuclear_segmentation_test.py, deepcell/applications/scale_detection.py, deepcell/applications/scale_detection_test.py, requirements.txt
* Replace the hard-coded model architecture and replace it with loading a model tar file from S3.
* Add `LabelDetection` and `ScaleDetection` applications.
* This makes the models themselves much more robust to small changes in the codebase. For example, if an architecture removes a layer, the application will not need to be retrained to be usable, as the saved model will still contain the removed layer.
=> Update Applications to use SavedModel format

.github/workflows/pypi.yaml, .gitignore, README.md, pyproject.toml, requirements.txt, setup.py
* Added PyPi deployment workflow.
* Updated `setup.py` for pip packages.
* Removed references to `compute_overlap` in `.gitignore`.
* Updated README with new badges and pip instructions.
* Pinned `numpy<1.19.0` for TensorFlow 2.3 compatibility.
* Enable `pip install deepcell`.
=> Use GitHub Actions to deploy pip packages

.github/workflows/test-docs.yaml, deepcell/applications/application.py, deepcell/applications/multiplex_segmentation.py, deepcell/callbacks.py, deepcell/image_generators/fully_convolutional.py, deepcell/layers/filter_detections.py, deepcell/model_zoo/fpn.py, deepcell/model_zoo/panopticnet.py, deepcell/model_zoo/retinamask.py, deepcell/utils/backbone_utils.py, deepcell/utils/export_utils.py, deepcell/utils/transform_utils.py, docs/source/.nitpick-ignore, docs/source/API/deepcell.model_zoo.rst, docs/source/conf.py
* Fix all warnings encountered in `sphinx-build`.
* Add `-W` to `sphinx-build` tests.
* Fix warnings and prevent new warnings from being introduced.
=> Fix warnings in docs and fail test-docs on warnings.

deepcell/applications/multiplex_segmentation.py
Redid the TF2 training of current multiplex model. Visual inspection + metrics confirms the hallucinations are gone. Closes #465.
=> Retrained multiplex model

setup.py
* Update version in `setup.py` to 0.8.4
* Pending new release.
=> Update version to 0.8.4

README.md, deepcell/_version.py
* Bump version to 0.8.5
* Get ready for pending patch release.
=> Bump version to 0.8.5

deepcell/applications/label_detection.py, deepcell/applications/scale_detection.py, notebooks/training/misc/Label-Detection-Model.ipynb, notebooks/training/misc/Scale-Detection-Model.ipynb
* Update architecture for `ScaleDetectionModel` and `LabelDetectionModel` for better flexibility with input image shape.
* Update both SavedModel file locations and hashes
* Change`fit_generator` to `fit` in both notebooks
* Fixes #421
=> Update ScaleDetectionModel and LabelDetectionModel

deepcell/image_generators/image_generators_test.py, deepcell/image_generators/tracking.py, deepcell/model_zoo/featurenet.py
* Update feature tensor shapes to support mutli-channel input data, as well as better support for `channel_first` formatting.
* Update tests for both grayscale and RGB images.
* Update tests to make assertions about output shapes.
* Fixes #150
* Fixes #149
=> Update SiameseDataGenerator for multi-channel data.

README.md
* Update README to reference incoming 0.9.0 version
* Help users use the latest version.
=> Update version used in README.

README.md
* Update Kiosk paper text.
* Add Mesmer paper to publications list.
* Update `scripts` folder to `notebooks` folder.
* Add new information to README.
=> Update README with new publications

deepcell/image_generators/__init__.py
* Add Semantic data generators to `data_generators.__all__`.
* Allow sphinx to build the docs, fixes #513.
=> Add Semantic data generators to data_generators.__all__.

.github/workflows/release-drafter.yaml
* Add `release-drafter` workflow YAML file.
* Automatically update release drafts on commits to master.
=> Add release-drafter workflow file to automatically release drafts.

Dockerfile, requirements.txt, setup.py
* Add `pydot>=1.4.2,<2` to `setup.py` and `requirements.txt`
* Install `graphviz` in the `Dockerfile`
* Enable use of `tf.keras.utils.plot_model` out of the box
* Fixes #504
=> Install `pydot` and `graphviz` to use `tf.keras.utils.plot_model`

deepcell/applications/cytoplasm_segmentation.py, deepcell/applications/nuclear_segmentation.py
* Update version of both Nuclear and Cytoplasm Segmentation models.
* These new models have been trained using the data registry and are the latest models available.
=> Update Nuclear and Cytoplasm Segmentation models.

.github/workflows/tests.yaml, deepcell/image_generators/image_generators_test.py, setup.py
* Include Python 3.9 in the GitHub Actions testing workflow.
* Update setup.py to include support for Python 3.9.
* TensorFlow 2.5.0 supports Python3.9 and so should DeepCell.
=> Support Python 3.9

notebooks/training/tracking/Training a Tracking Model.ipynb
=> Update Training a Tracking Model.ipynb

.github/workflows/docker-image.yaml, Dockerfile, README.md, setup.py
* Update TF_VERSION used to [2.5.2](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.2)
* Fixes several vulnerabilities
=> Bump TF_VERSION to 2.5.2.

README.md
* Update the ReadMe with the link for the paper
* I'll merge this in tomorrow AM once the link goes live
=> Update README with TissueNet publication

.github/workflows/tests.yaml
* Add a new GitHub workflow to build a docker image and run the unit tests inside it.
* This ensures that the docker images work as expected rather than relying solely on the tests passing in the test-runner environment.
=> Build a Docker image and run tests in the container.

README.md, deepcell/_version.py
* Update copyright in `deepcell/_version.py` to 2022
=> Bump version to 0.11.1

README.md
All-
Someone in the OME community recently ran into some confusion with the licensing of deepcell-tf. The license badge lists "Apache 2.0" but the LICENSE file states "Modified Apache 2.0". This proposes use of [![Modified Apache 2.0](https://img.shields.io/badge/license-Modified%20Apache%202-blue)](https://img.shields.io/badge/license-Modified%20Apache%202-blue) to increase the clarity.
All the best,
~Josh Moore
<details><summary><code>diff LICENSE-2.0.txt LICENSE</code></summary>
```
--- LICENSE-2.0.txt     2022-04-01 14:41:12.806279265 +0100
+++ LICENSE     2022-04-01 14:41:45.921931426 +0100
@@ -1,7 +1,5 @@
-
-                                 Apache License
+                            Modified Apache License
Version 2.0, January 2004
- …
```
=> Update license badge ("Modified Apache 2.0")

Dockerfile, deepcell/applications/mesmer.py
Update the mesmer model from model-registry#15. I'll leave this PR as a draft until @ngreenwald has a chance to test post-processing parameters and determine if any changes are needed.
=> Update MultiplexSegmentation model

deepcell/data/tracking.py, deepcell/utils/tracking_utils.py, requirements.txt, setup.py
* Bump `deepcell-tracking` to the new minor release
* Update imports to match the reorganization introduced in this release
=> Bump `deepcell-tracking` to 0.6.0

deepcell/utils/backbone_utils.py
* Add support for EfficientNetV2 backbones to the get_backbone utility function
* Exposes EfficientNetV2 backbones for use in deepcell model architectures
=> Add support for EfficientNetV2 backbones to the get_backbone utility function

deepcell/applications/cell_tracking.py, deepcell/applications/nuclear_segmentation.py
Updates the nuclear segmentation model from model-registry #34 and the tracking model from model-registry #36
=> Bump model versions for nuclear segmentation and tracking

Dockerfile, requirements.txt
* Removed jupyter notebook call
=> Update Dockerfile to jupyter lab

.github/workflows/tests.yaml, pytest.ini, requirements-test.txt, requirements.txt, setup.py
Add support for Python 3.10
General software updates. See also vanvalenlab/deepcell-tracking#111 and vanvalenlab/deepcell-toolbox#128
=> Add python3.10 support

deepcell/_version.py, docs/source/conf.py
* Bump version numbers in final step before next patch release
=> Prepare for 0.12.5 release

deepcell/applications/cell_tracking.py, deepcell/applications/nuclear_segmentation.py, deepcell/utils/io_utils_test.py
This PR updates the models used by the `NuclearSegmentation` and `CellTracking` applications to the latest versions associated with the upcoming paper.
=> Update nuclear tracking and segmentation model paths

deepcell/applications/application.py, deepcell/applications/label_detection.py, deepcell/applications/mesmer.py, deepcell/applications/scale_detection.py, deepcell/callbacks.py, deepcell/image_generators/__init__.py, deepcell/image_generators/fully_convolutional.py, deepcell/image_generators/sample.py, deepcell/image_generators/scale.py, deepcell/image_generators/semantic.py, deepcell/image_generators/tracking.py, deepcell/layers/normalization.py, deepcell/model_zoo/fpn.py, deepcell/model_zoo/panopticnet.py, deepcell/model_zoo/tracking.py, deepcell/utils/data_utils.py, deepcell/utils/plot_utils.py, docs/source/conf.py
* Applying linting changes from ruff-0.0.284
* Mostly to clean up the diff in #678
=> Apply ruff-0.0.284.

deepcell/_version.py, docs/source/conf.py
* Release v0.12.8
* Add SpotNet dataset to authenticated datasets.
=> REL: v0.12.8

.github/workflows/docker-image.yaml, .github/workflows/lint.yaml, .github/workflows/pypi.yaml, .github/workflows/test-docs.yaml, .github/workflows/tests.yaml, .readthedocs.yml, deepcell/applications/cell_tracking.py, deepcell/datasets/dataset.py, deepcell/datasets/spot_net.py, deepcell/datasets/tissue_net.py, docs/source/.nitpick-ignore, docs/source/API-key.rst, docs/source/applications/caliban.py, docs/source/applications/mesmer.py
* Updates action versions and modifies the `ruff` incantation to use the new flag now that `ruff-format` exists
* The inexorable march of time
=> CI: Update action versions and ruff incantation

deepcell/layers/temporal.py, deepcell/model_zoo/tracking.py
Also adds a flag to make the image normalization layer in the tracking appearance head configurable
=> Correct the axis which temporal merges are applied to in tracking model

deepcell/applications/cell_tracking.py, deepcell/applications/nuclear_segmentation.py, deepcell/datasets/dynamic_nuclear_net.py
- Update Dynamic Nuclear Net with addition of Hela CTC movies to version 1.1
- Update nuclear segmentation and tracking models after retraining on the updated dataset
=> Update DNN dataset and Caliban models
