vanvalenlab/deepcell-tf

.github/stale.yml

Stalebot will automatically mark 3-month-old issues as stale.  If there is no further activity for 30 more days, the issue will be automatically closed.

Automatically close stale issues

---

Dockerfile
deepcell/layers/padding.py
deepcell/training.py
deepcell/utils/train_utils.py
requirements.txt

Using tf.keras `multi_gpu_model` to enable multiple GPU training when available.  To enable saving (and loading) of models using `multi_gpu_model`, it is wrapped in a parent class that holds the original series model as an attribute, which it uses to save and load models.
Additionally, there are some small requirements for using `skip_connections` with multi_gpu_models.  Namely 1) the training data must be divisible by the number of GPUs, and 2) the validation data must be bigger than the number of GPUs.  this PR silently shaves off any training data that is uneven, but if the validation data is too small, a descriptive error is thrown.

enable training on multiple GPUs

---

deepcell/image_generators.py
scripts/deepcell/DeepCell Transform 3D Fully Convolutional.ipynb
scripts/watershed/Watershed Transform 2D Fully Convolutional.ipynb
scripts/watershed/Watershed Transform 2D Sample Based.ipynb
scripts/watershed/Watershed Transform 3D Fully Convolutional.ipynb
scripts/watershed/Watershed Transform 3D Sample Based.ipynb
tests/deepcell/image_generators_test.py

Instead of a None transform changing data to `fgbg` (background, not background), None will just call `to_categorical` on the data provided.  This is a good catch-all for new data that will be semantically segmented, but likely not instance segmented.
Meanwhile, `"fgbg"`  has been added as a distinct transform key.  It behaves as before, and all notebooks have been updated to use the "fgbg" key instead of None.

Add "fgbg" as transform key.

---

Dockerfile
README.md
requirements.txt

Deprecating the nvidia base image, as users will need to make an account in order to use this.  Additionally, `tensorflow/tensorflow` has base images that compile for both CPU and GPU, which we can leverage in creating builds for `deepcell` for both CPU and GPU as well.  This base image is a required step in getting CPU and GPU builds, but these will likely need to be automatically generated, or the user will be told what version to use.
Fixes #115 
Related to #107 
Related to #105

Use tensorflow/tensorflow as base image

---

README.md

The notebooks names were changed during codebase cleanup, but the links to the newly changed files were not updated.
This PR Updates the links for the deepcell notebooks, which fixes #128

fix README links to deepcell notebooks

---

deepcell/datasets/hek293.py
deepcell/datasets/nih_3t3.py
deepcell/datasets/tracked/hek293.py

The datasets have been updated to remove errors.  This changes the hash in the `get_file` call inside `deepcell.datasets`.

Refreshed the example datasets

---

deepcell/image_generators.py
deepcell/utils/transform_utils.py
tests/deepcell/image_generators_test.py
tests/deepcell/utils/transform_utils_test.py

Allow the `deepcell` transform to separate edges into cell-cell and cell-background edges with the `separate_edge_classes` boolean flag.
This PR resolves #168

Add `separate_edge_classes` switch to deepcell transform

---

deepcell/model_zoo/featurenet.py

Fixed bug where ZeroPadding3D was not being fed a previous input.
Update featurenet `multires` flow to always create the list. dangerous to only have the list defined sometimes.

FeatureNet bug fixes

---

deepcell/image_generators.py

There were several conditional `if panoptic` branches that have been simplified to use empty lists if not panoptic.  This should prevent any future issues with variables not being defined due to `panoptic` boolean values.

Simplify RetinaNetGenerator

---

.travis.yml
Dockerfile
requirements.txt

Use `sed` to change the prevent installation of tensorflow in the travis tests and Dockerfile build stages.  Travis will push an image for both GPU and CPU once tests complete.
The Dockerfile has also been updated to support the newer base images of tensorflow that no longer use `jupyter` by default.
Fixes #107

Travis builds and pushes both CPU and GPU based docker images.

---

.travis.yml
requirements-test.txt

Travis seems to install different/incompatible versions with `pip` that lead to some tests failing due to `pytest`.  This PR pins all the testing dependencies and moves them to a `requirements-test.txt` file, so that they can be directly installed with `pip install -r requirements-test.txt`.

Pin test dependencies to resolve TravisCI testing issues.

---

.travis.yml
deepcell/applications/label_detection_test.py
deepcell/applications/nuclear_segmentation_test.py
deepcell/applications/phase_segmentation_test.py
deepcell/applications/scale_detection_test.py
deepcell/layers/filter_detections_test.py
deepcell/layers/location_test.py
deepcell/layers/normalization_test.py
deepcell/layers/padding_test.py
deepcell/layers/pooling_test.py
deepcell/layers/resize_test.py
deepcell/layers/retinanet_test.py
deepcell/model_zoo/featurenet_test.py
deepcell/model_zoo/maskrcnn_test.py
deepcell/model_zoo/retinanet_test.py
deepcell/utils/backbone_utils_test.py
requirements.txt

`scikit-image` has a dependency on `PyWaveletts` which was just re-released today. This new vesion of PyWavelets does not support python2.7.  Pin the version of pywavelets to 1.0.3 to resolve this issue.
`test_session(use_gpu=True)` has been replaced with `test_session`.
Python2 tests all backbones, as get_backbone bug was resolved in #239

Pin PyWaveletts to 1.0.3 in requirements.txt

---

requirements.txt

the PyWavelets tarball for 1.1.0 was incompatible with python2.7 but was installed by default in skimage's setup.py.  PyWavelets was upgaded to 1.1.1 (1.1.0 deleted) and the issue is resolved.

remove PyWavelets from requirements as python2.7 skimage bug is resolved.

---

deepcell/layers/normalization.py
deepcell/layers/normalization_test.py

For the `ImageNormalization` layers, adding a weight for the kernel can cause errors when loading the weights with a different input shape. By removing the `self.add_weight` call, we can prevent this issue.  Instead of weights, we can just use `self.kernel = W` directly.
---
Resolves #249

Remove weights from ImageNormalization layers.

---

deepcell/utils/data_utils.py
deepcell/utils/data_utils_test.py

updated utils.data_utils.reshape_matrix to support non-square input images and non-square output images (by allowing a length 2 input reshape_size).
In the previous version, non-square input images could result in an error or in output images that did not include a part of the input image.

Reshape matrix fix

---

README.md

It looks like the latest version is using python 3.6. I had to change the mounting path in order to get file changes to sync to docker. Should update the readme for appropriate mounting of containers (unless this is a result of me doing something wrong)

Update README with python version

---

deepcell/layers/retinanet.py
deepcell/layers/retinanet_test.py

From  [the same PR in keras-retinanet](https://github.com/fizyr/keras-retinanet/commit/5524619f91699732ba24c6f52fb9e4b0b780b019).

Correct upper limit for clipping boxes.

---

deepcell/layers/filter_detections_test.py
deepcell/layers/location_test.py
deepcell/layers/normalization_test.py
deepcell/layers/padding_test.py
deepcell/layers/pooling_test.py
deepcell/layers/resize_test.py
deepcell/layers/retinanet_test.py
deepcell/layers/tensor_product_test.py
deepcell/layers/upsample_test.py
deepcell/utils/testing_utils.py

The TensorFlow 1.14.0 release has updated the `layer_test` function.  It is still incompatible with `custom_objects`, so the testing_utils file has been updated appropriately.

Update test_utils.py from TensorFlow 1.14.0

---

deepcell/image_generators/__init__.py
deepcell/utils/transform_utils.py
deepcell/utils/transform_utils_test.py

The current implementation of the pixel transform first identifies all unique label IDs in all stacks of training images, then loops over each ID, then over each crop. 
The current implementation of the watershed transform instead first loops over each crop, then identifies the unique cell IDs within each crop, and then loops over each unique label ID.
The latter results in significant speed increases, as only the label IDs within each crop are iterated over. 
This PR refactors the pixel transform in the same style as watershed. 
Obviously a bug here would have far-reaching consequences, so please feel free to go over this with a fine-toothed comb. Happy to make any changes!

Speeding up the pixel transform

---

deepcell/utils/transform_utils.py
deepcell/utils/transform_utils_test.py

When I modified the pixel transform for #286, I accidentally removed two layers of the for loop. I should have just removed the first. This resulted in only the last cell in each crop being transformed, rather than every cell in the crop. Closes #294

fix pixel transform bug

---

deepcell/datasets/cytoplasm.py

Resolves #297 
---
The filepath was missing the "512" at the end of the filename.

Fix filepath for cytoplasm A549 dataset

---

README.md

* Updated the relative path to link to the tracking notebook from the README.
* The link is currently broken and sends to a 404.

Fix broken tracking notebook link.

---

CONTRIBUTING.md
deepcell/datasets/cytoplasm.py
deepcell/datasets/phase.py
deepcell/datasets/tracked.py

* Swap out the current pointers to the cytoplasmic data to new files that have been computationally curated. There are 2 new files (one fluorescent and one phase). Each file is composed of many cell lines. 
* Necessary updates to data with more accurate annotations.
* Fixes #296
* Fixes #298
* Fixes #309

Update cytoplasmic data in DeepCell Datasets

---

README.md

* Add the license badge back to the README with the link pointed at our own license.
* Badges look nice, but we just needed to fix the link.

Add license badge referencing the local LICENSE file.

---

README.md

* Fix LICENCSE link pointing to the wrong repository.
* This is a bugfix due to a bad copy/paste.

update URL for license, deepcell-tf not kiosk.

---

deepcell/model_zoo/fpn.py
deepcell/model_zoo/panopticnet.py

* Add an option to `deepcell.model_zoo.fpn.create_pyramid_levels` that enables choosing between `UpsampleLike` and `Upsampling2D`
* Use `Upsampling2D` in panoptic models instead of `UpsampleLike`
* In `deepcell.model_zoo.panoptic.semantic_upsample` use only the final layer of the pyramid network to blow up to final image size instead of adding together all layers in the pyramid.
* These changes to upsampling procedures reduces the overall memory footprint of the model and speeds up computation time. The lower memory profile means that this model will be more compatible with hosting multiple models through tf-serving.

Change panoptic upsampling method to reduce memory and speed consumption

---

deepcell/applications/application.py
deepcell/applications/application_test.py

* Correct calculation of image size for rescale in application objects
* The original calculation was the inverse of what it should have been

Correct calculation of image size for rescale

---

deepcell/image_generators/__init__.py
deepcell/utils/transform_utils.py

* Updated documentation
* DRYed out the `*_movie` functions to just use the 2d on each frame (same code).
* Support old transform names but use a `DeprecationWarning`.
* Get the simplify-transforms branch in good shape.

Improvements to the simplify-transforms branch

---

requirements.txt

* Pin the highest version of `skimage` to 0.16.2.
* `skimage` 0.17.0 and up have moved / removed the `external` module.
* Fixes #385

pin skimage to 0.16.2 at most to fix #385

---

requirements.txt

* A new `keras-preprocessing` release has broken the tests for `ImageDataGenerators`.
* Pinning the version fixes the issues and restores expected behavior.

Pin keras-preprocessing to <= 1.1.0

---

deepcell/image_generators/__init__.py

* The 'centroid' transform for semantic generators was skipped over, leading to an error if specified
* Allows centroid to be used

Centroid transform bugfix

---

deepcell/applications/application.py
requirements.txt

* Bump `deepcell_toolbox` to 0.4.1 to fix `resize()` bug where `cv2` would swap the x and y axes.
* Don't swap outputs of `Application.resize`
* Bug fixed upstream, no need to account for its errant behavior anymore.

Upgrade deepcell_toolbox to account for swapped axes in Application.resize()

---

deepcell/model_zoo/fpn.py

* Removed `n_filters` from the final `semantic_upsample` call in `fpn.__create_semantic_head`.
* This was passed through erroneously and made the previous model version unusable.

Fix create_semantic_head to ignore n_filters in final semantic_upsample

---

.travis.yml
deepcell/callbacks_test.py
deepcell/initializers_test.py
deepcell/layers/convolutional_recurrent_test.py
deepcell/layers/filter_detections_test.py
deepcell/layers/location_test.py
deepcell/layers/normalization_test.py
deepcell/layers/padding_test.py
deepcell/layers/pooling_test.py
deepcell/layers/resize_test.py
deepcell/layers/retinanet_test.py
deepcell/layers/tensor_product_test.py
deepcell/layers/upsample_test.py
deepcell/losses_test.py
deepcell/model_zoo/featurenet_test.py
deepcell/model_zoo/panopticnet_test.py
deepcell/model_zoo/retinamask_test.py
deepcell/model_zoo/retinanet_test.py

* Testing 2.1.1 and 2.2.0
* Removed unsupported python2.7
* To be able to test TF2 migration branch with travis.
---
Some outstanding issues with TF2 migration:
- `ConvGRU` layer
- Invalid Data tests for data generators
- `RetinaMovie` data generator
- `RetinaMask` tests are failing

Update .travis.yml with TensorFlow2 versions.

---

deepcell/applications/application.py
deepcell/applications/application_test.py
deepcell/applications/multiplex_segmentation.py
deepcell/applications/multiplex_segmentation_test.py
requirements.txt

* Updates the multiplex_segmentation app to support models that predict multiple distinct cellular compartments. 
* To enable predicting both nuclear and whole-cell signal
I put the new postprocessing function in here just to make it easier to review both together. Once you're both happy with the approach and implementation I'll migrate to a separate PR in deepcell-toolbox.
I changed some of the kw arguments in the postprocessing function because I think the ones we're currently using aren't that intuitive. However, if you think that is going to cause confusion I can switch them back to match the existing defaults.

Updated multiplex app and new postprocessing function

---

deepcell/utils/transform_utils.py

* Switches behavior in pixelwise transform to match new functionality in vanvalenlab/deepcell-toolbox#46 for the other transforms
* Results in much faster augmentation during preprocessing
Closes #403 
Combined with the changes to erode_edges, this takes the preprocessing time from ~80 minutes to 6 minutes for the current multiplex dataset. 
Shown here is the amount of time for each transform:
The first set of times is for whole-cell annotations, and the second is for nuclear annotations. Because not all of the cells have an observed nucleus, there are fewer annotations in the second loop. 
There are 211377 cells in the whole-cell annotations, and 155603 annotations in the nuclear annotations. 
The two transforms that are now taking up the bulk of the remaining time, the inner- and …

Faster pixelwise transform

---

requirements.txt

* Pin `opencv-python<=3.4.9.31` instead of `<4`.
* This was the last version that supports Python2.7. We will abandon support, but this fix allows us to maintain compatibility until then.

Pin opencv-python<=3.4.9.31 to maintain compatibility with older Python distributions

---

deepcell/applications/cell_tracking.py
deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/label_detection.py
deepcell/applications/multiplex_segmentation.py
deepcell/applications/nuclear_segmentation.py
deepcell/applications/scale_detection.py

* Update the hash for the `MultiplexSegmentation` application.
* Change applications from using the deprecated argument `md5_hash` to `file_hash`.
* Prevent redundant downloads of the model weights.
* `md5_hash` is deprecated.

Update hash for MultiplexSegmentation model and use file_hash instead of md5_hash.

---

deepcell/training.py

* Instead of saving the final model weights, rely on the ModelCheckpoint callback to save the best weights.
* Saving the final model weights may overwrite better model weights from a previous epoch.
* Closes #290

Only save the best model weights in training.py functions.

---

deepcell/applications/__init__.py
deepcell/applications/cell_tracking.py
deepcell/applications/cell_tracking_test.py
deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/multiplex_segmentation.py
deepcell/applications/multiplex_segmentation_test.py
deepcell/applications/nuclear_segmentation.py
notebooks/applications/Nuclear-Application.ipynb

* Convert `CellTrackingModel` to `CellTracking` application object.
* Update `NuclearSegmentation` and `CytoplasmSegmentation` to only download imagenet weights when `use_pretrained_weights is True`. 
* Add `normalize` to `NuclearSegmentation` pre-processing.
* Fix whitespace in applications for readability
* Close vanvalenlab/deepcell-tracking#28.
* Prevent downloading weights for models during testing.
* Improve code quality of applications.
* Fix bug in nuclear segmentation causing poor quality segmentations (new weights must have been trained with normalized nuclear data).

Create CellTracking application object, various application bugfixes.

---

.github/workflows/docker-image.yaml

* Change the way the git tags are parsed for docker tags.
* Allows docker images to be properly tagged.

Fix docker deployment workflow

---

.github/workflows/docker-image.yaml

* Change the docker-image workflow to run on `published` releases, not `created` ones.
* `created` releases will not trigger if the release was first a draft. This is not ideal since we often draft releases well ahead of time.

Build docker images for all published releases.

---

.github/workflows/docker-image.yaml

* Fix bug in defining `build-args` using the environment variable `TF_VERSION`.
* To enable proper tagging of released docker images.

Fix build-args in docker-image workflow

---

Dockerfile

* Include the `README.md` file in the Docker image
* `README.md` is now required to install `deepcell` via `setup.py`.

COPY README.md into Docker container for setup.py installation

---

Dockerfile
README.md
requirements.txt
setup.py

* Replace `opencv-python` with `opencv-python-headless`
* Update `deepcell-toolbox` to 0.8.3
* Update `deepcell-tracking` to 0.2.7
* `opencv-python` installs Qt and other GUI dependencies for the GUI, while `opencv-python-headless` does not.
* The docker image no longer needs to install `libsm6`, `libxrender-dev`, or `libxext6`, leading to faster build times and smaller images.

Use headless openCV for faster builds and smaller images.

---

deepcell/applications/application.py
deepcell/applications/application_test.py

* `Application._resize_output` wraps the input in a list if its a single tensor, and resizes every tensor in the output
* Allow output from postprocessing with multiple outputs to be resized properly (e.g. if `postprocess_function=None`).

Application._resize_output handles both single and multiple tensor inputs.

---

deepcell/applications/application.py
deepcell/applications/nuclear_segmentation.py
requirements.txt

* Update `deepcell-toolbox` to 0.8.4.
* Add optional `pad_mode` argument to `Application._predict_segmentation` and other methods to allow overriding the default padding mode of `"constant"`.
* The `NuclearSegmentation` application has much better performance with `"reflect"` padding mode, and this allows future applications to easily change their padding mode.

Allow Applications to override default padding mode in _tile_input.

---

.github/workflows/tests.yaml

* Split PyTest and Coveralls into separate build stages (which was not supported when GitHub Actions was originally adopted).
* Conditionally run Coveralls steps only if `COVERALLS_REPO_TOKEN` is set.
* This allows forked PRs to be submitted without failing due to a missing `COVERALLS_REPO_TOKEN`.

Split PyTest and Coveralls stages & conditionally skip Coveralls if token is unset.

---

requirements.txt
setup.py

* Update minimum dependencies.
* Raise the floor for some older dependencies (numpy and opencv especially)
* Update to latest version of `deepcell-toolbox` and `deepcell-tracking` to get latest bugfixes.

Update deepcell-toolbox and deepcell-tracking to latest versions.

---

deepcell/utils/io_utils.py
deepcell/utils/io_utils_test.py
requirements.txt
setup.py

* Updated `io_utils.py` to be compatible with new versions of `scikit-image`.
* `scikit-image` was previously pinned to `<17` which is several major versions behind.

Remove scikit-image version upper bound

---

deepcell/applications/application.py
deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/cytoplasm_segmentation_test.py
deepcell/applications/nuclear_segmentation.py

* Add basic logging to the base class `Application`.
* Change the `NuclearSegmentation` preprocessing from `histogram_normalization` to `normalize`.
* Update the `CytoplasmSegmentation` to use a new TensorFlow 2 based model.
* Logging makes the pre and post-processing steps and performance more visible (for use in downstream applications like the `kiosk-redis-consumer`.
* The `NuclearSegmentation` model was trained with `histogram_normalization` but not on padded data. Because `Application._tile_input` pads all around the edge (zero-paddings by default) the performance of `histogram_normalization` is quantitatively worse than `normalize`. In future versions, we will train on zero-padded and reflection padded data which should resolve this inconsistency.
* The `CytoplasmSegmentation` model …

Patches for deepcell.applications

---

.github/workflows/pypi.yaml
README.md
deepcell/_version.py

* Change the `sed` command in the `deploy-cpu` PyPI build stage.
* #482 changed the location of the package name from `setup.py` to `deepcell/_version.py` but did not change the deployment script, causing the PyPI release to fail.

Update sed target to fix package name in deepcell-cpu deployment script.

---

deepcell/image_generators/semantic.py

* The `save_to_dir` block has been moved out of the `index_array` for loop, which was duplicating the saved images for every item in the batch.
* Fixes a bug in the `SemanticMovieIterator` that saves too many images.

SemanticMovieIterator saves duplicate images for every batch.

---

deepcell/applications/label_detection.py
deepcell/applications/scale_detection.py

* Revert the published V2 models back to V1.
* V2 models were not performing well and there is no need to change the SavedModel alongside an updated architecture.

Revert ScaleDetection and LabelDetection to v1 models.

---

deepcell/_version.py
requirements.txt
setup.py

* Update `deepcell` version to 0.9.0.
* Pin `deepcell-toolbox` to 0.9.x.
* Pin `deepcell-tracking` to 0.3.x.
* Update `deepcell-toolbox` to the latest version but prevent upgrading to future breaking changes.

Update toolbox to 0.9.x and pin tracking to 0.3.x.

---

pytest.ini
setup.py

* Added missing `<` character.
* Allow `pypi` to read `setup.py`.

Fix typo setup.py deepcell-tracking version maximum.

---

deepcell/callbacks.py
deepcell/callbacks_test.py

* Add new `InferenceTimer` callback to measure inference time for a pre-defined number of samples:
```
Average inference speed per sample for 100 total samples: 0.00204s ± 0.00158s.
```
* Fixes #275

InferenceTimer callback to measure inference time during training.

---

deepcell/data/tracking.py
deepcell/losses.py
deepcell/model_zoo/tracking.py

* Update several layers for using (batch, time, node, channels) as input data rather than (batch, node, time, channels).
* Updated the loss to have the expected output shape.
* Pull out some methods as custom classes `Comparison` and `DeltaReshape`.
* The time axis is required to be first to avoid data leaks in the reshapes (for the neighborhood encoder).
* Using custom layers prevents the need for loading a model with `custom_objects`.

Refactor GNNTrackingModel for time-axis first data. 

---

deepcell/data/__init__.py
deepcell/data/tracking.py
deepcell/datasets/builders.py
deepcell/losses.py
deepcell/losses_test.py
deepcell/model_zoo/tracking.py

* Break the `TrackingDatasetBuilder` class into several helper functions that more resemble the `tf.data` docs.
* Updates the `temporal_slice` augmentation function for time-axis first.
* The `TrackingDatasetBuilder` is confusingly named (as it is NOT a `tf.datasets.DatasetBuilder`)
* The bulk of the code that makes up the `TrackingDatasetBuilder` has been made obsolete by the `deepcell_tracking.utils.concat_tracks` function, which completely replaces the `_load_tracks()` method on the Builder.
* The other augmentation functions are stateless and have been migrated to `deepcell.data.tracking`.
* I think that mimicking the `tf.data` nomenclature is more clear that the `deepcell.datasets.builders`.  `deepcell.data` is for working with `tf.data` and `deepcell.datasets` provides access to …

Break the TrackingDatasetBuilder into `deepcell.data.tracking` functions.

---

deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/nuclear_segmentation.py

* Set `preprocessing_fn` and `postprocessing_fn` as arguments to `init` to allow them to be overridden when creating applications.
* This allows the applications to be more flexible and prevents users from subclassing the Application when they use a different preprocessing function.

Allow preprocessing_fn and postprocessing_fn to be overridden.

---

deepcell/applications/cytoplasm_segmentation.py

Enables overriding the default `pad_mode` to use "reflect" by default.
* Add `pad_mode` as a new argument to `CytoplasmSegmentation.predict` with default value `"reflect"`.
* Allows overriding the padding mode for tiling the input. Prevents edge effects for models not trained on zero-padded data.

Add `pad_mode` as an argument to `CytoplasmSegmentation.predict`.

---

.github/release-drafter.yml

* Update the `release-drafter.yml` template to add the "dependencies" label to the Maintenace category.
* These are regularly labeled PRs and should get filed under maintenance.

Add dependencies labels to Maintenance category

---

deepcell/model_zoo/tracking.py

* Create keras layer `Unmerge` used to unmerge embeddings and centroids.
* Change default `merge_type` for `get_embedding_temporal_merge_model` and `get_delta_temporal_merge_model` to lstm instead of cnn
* Remove residual connections in `get_tracking_decoder` 
* Nicer to have a keras layer than use Lambda layers
* Merging the embeddings depends only on timepoints in the present and past, and thus do not have information from future embeddings. Cnn's use information from future timepoints, resulting in temporal information being leaked. Lstm's only use information from the current and old embeddings (which is what we want).
* Adding the residual connections does not help with accuracy

Graph tracking model architecture changes

---

deepcell/layers/__init__.py
deepcell/layers/temporal.py
deepcell/layers/temporal_test.py
deepcell/model_zoo/tracking.py

* Move new custom layers from `model_zoo` to `layers/temporal.py`
* Add tests for moved layers.
* Merge `TemporalMerge` and `TemporalUnmerge` with the LSTM layer.
* Add back in the fully connected layers. Training is much improved (6 correct -> 18 correct)
* Remove `time_window` and allow user to pass `appearance_shape`. Appearance encoder convolutions are defined by `log(app_shape[0], 2)`.
* Staying organized and improving coverage.
* Resolve hard-coded values
* DRY out the model zoo.

Move custom layers into `layers/temporal.py` and add tests.

---

deepcell/applications/application.py
deepcell/applications/application_test.py

Modifies the applications to use internal batch prediction function rather than the default model.predict batching functionality. Closes #538 
The default model.predict batch function creates a tf.dataset object with all images, not just the specified batch size. This leads to memory issues on the GPU when batch processing tiles from large images.

Application batch prediction

---

.github/workflows/docker-image.yaml
Dockerfile
deepcell/_version.py
requirements.txt
setup.py

* Update TensorFlow to the latest 2.3.x release.
* Updates the compatible releases of TensorFlow 2.3.x to allow patch releases, as TensorFlow 2.3.1+ does not support Python 3.5.
* Fixes lots of [CVEs](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.4)

Update TensorFlow to 2.3.4.

---

deepcell/_version.py

* Bump version to `0.10.0-rc.1`, the first release candidate for the pending `0.10.0` release.
* #530 and #545 will be addressed before final release comes out, but pre-release will enable users to begin using the new functionality.

Bump version to 0.10.0-rc.1

---

.github/workflows/pypi.yaml
deepcell/_version.py

* Use `sed` to replace `tensorflow~=` with `tensorflow-cpu~=`. Including the `~` prevents other deps that start with the word `tensorflow` from getting replaced.
* Bump version to 0.10.0-rc.2
* Fixes #547

Fix `sed` commands to only replace `tensorflow` not `tensorflow-addons`.

---

deepcell/_version.py
deepcell/applications/cell_tracking.py
deepcell/model_zoo/tracking.py

* Remove the Fully Connected layers from the tracking decoder
* Enable multiple graph convolutional layer types with new `graph_layer` argument, currently supports GCN and GCS.
* Improve model performance and ease of use.

Remove fully convolutional layers from the GNNTrackingModel.

---

deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/nuclear_segmentation.py

* Updates nuclear segmentation model with the version created by https://github.com/vanvalenlab/data-registry/pull/188
* Update cytoplasm segmentation model with the version created by https://github.com/vanvalenlab/data-registry/pull/164
The same models have been uploaded to the deepcell-models bucket in GCP for deployment through the kiosk.

Update nuclear and cytoplasm segmentation models from the data-registry

---

deepcell/model_zoo/tracking.py

* Exposes an option to use the graph attention layer `GATConv` from `spektral`
* Allows us to test the impact of different graph layers on the tracking model

Add option for graph attention layer to tracking model

---

docs/requirements-docs.txt

* Pins `jinja2<3.1` in `docs/requirements-docs.txt`
* The new `jinja2` release deprecates functions that are required for `sphinx`.

Pin `jinja2<3.1` to restore functional docs builds

---

deepcell/applications/cell_tracking.py

* The nuclear tracking model has been updated in the model registry. This PR redirects the current pointers to grab this new version. The division parameter has also been updated to match the result of the latest parameter sweep.
* The applications should match the latest verified version from the model registry.

Update tracking parameters and hashes for new models

---

deepcell/_version.py
deepcell/model_zoo/tracking.py

* Provide the option to select either `BatchNormalization` or `LayerNormalization` in `GNNTrackingModel`
* This option makes it possible to train the model with a batch size of 1 when layer normalization is enabled.

Add option for either batch or layer norm in tracking model

---

README.md
deepcell/_version.py
deepcell/applications/cell_tracking.py
deepcell/applications/cytoplasm_segmentation.py
deepcell/applications/mesmer.py
deepcell/applications/nuclear_segmentation.py

* Update models with versions that were trained on tensorflow 2.8 (https://github.com/vanvalenlab/model-registry/pull/17)
* Models should use the same version of tensorflow for predictions as they were trained on

Update models after retraining on deepcell 0.12.0rc

---

deepcell/applications/mesmer.py

Doc-string for `format_output_mesmer` is now correctly saying "ValueError: if model output list is not len(4)" 
Because `format_output_mesmer` code diverged from the doc in what is expected length of model output list

Update the docstring for `format_output_mesmer`

---

deepcell/data/tracking.py
deepcell/model_zoo/tracking.py

* Fixed a bug that required the tracking model to have n_filters, encoder_dim, and embedding_dim be pinned to 64
* Model optimization is going to require us to change these parameters to improve performance and reduce model size. This pull request makes that substantially easier by fixing this bug.

Fix tracking model bug that pinned n_filters, encoder_dim and embedding_dim to 64

---

deepcell/data/tracking.py
deepcell/model_zoo/tracking.py
requirements.txt
setup.py

* Modify the Track class so that it allows hooks into get_image_features for crop_mode and norm
* Creating the appearance image feature by cropping and resizing removes information about cell size that the model can use to make more accurate tracking predictions. A previous update to deepcell-tracking (https://github.com/vanvalenlab/deepcell-tracking/pull/98) introduced the crop_mode (either 'fixed' or 'resize') and norm flags to get_image_features. This pull request exposes these flags to the Track class.

Expose option for fixed crops in the Track data object

---

README.md
deepcell/_version.py
docs/requirements-docs.txt
docs/source/conf.py

Bump version number for new release
Also includes a change from `m2r` to `m2r2` for our documentation pipeline. `m2r` is no longer being maintained so it has been replaced with a fork with more active maintenance. https://github.com/CrossNox/m2r2

Swap m2r with m2r2 and update version number to 0.12.3

---

deepcell/_version.py
pyproject.toml
requirements.txt
setup.py

Pinning numpy and creating a patch release to avoid errors related to the latest updates in numpy v1.24
Resolve failures in deepcell due to code that depends on numpy features that were removed in 1.24. This affects the entire deepcell ecosystem of libraries; see also: vanvalenlab/deepcell-toolbox#131 and vanvalenlab/deepcell-tracking#110

MAINT: Pin numpy to avoid errors due to expired scalar deprecations

---

docs/requirements-docs.txt
docs/source/conf.py
notebooks/training/tracking/Training and Tracking with GNNs.ipynb

The major change is removing the pins to sphinx, docutils, etc. AFAICT the motivating factors for the pins are no longer relevant - see e.g. #320 and #526.
Some other minor changes include:
- Minor configuration updates to get rid of warnings
- Updating intersphinx to point to the stable Python docs instead of 3.7
- Modifying the heading levels in one of the example notebooks to fix the toctree nav column
Sphinx 2.3.1 is 2 major releases behind stable - being pinned this far back will make it difficult to reliably change/update the docs.

A collection of minor documentation updates

---

.github/workflows/tests.yaml

This should help catch incompatibilities between unreleased versions of libraries in the deepcell ecosystem.
* Code remains unaffected - this PR is just dedicated to bolstering testing infrastructure
* The deepcell- libraries are interdependent: `deepcell-tf` depends on `deepcell-tracking` and `deepcell-toolbox`. If there is a change in one of these dependencies, there is no way to tell in the automated test running whether this will break something in `deepcell-tf` until the underlying libraries are released. Testing against the dev branches will catch potential issues sooner, at the expense of being noisier and reducing test specificity (failures can originate from either *deepcell-tf* or the dependencies). Overall however I think this should improve the ability to things consistent …

Add CI testing against dev branches of deepcell-toolbox and deepcell-tracking

---

deepcell/model_zoo/panopticnet_test.py

Closes gh-643. If there's a reason not to use the `nsc2` input, then alternatively we can delete that var.
See gh-643 for context.

Update test to use second num_semantic_classes input.

---

deepcell/utils/export_utils.py

Deprecate `export_utils.export_model_to_tflite`.
Notify users who may still be using this function to switch to `tf.keras.models.save_model`. Closes gh-645.

Deprecate export_model_to_tflite

---

deepcell/utils/__init__.py

A followup to #648. With the deprecation of `export_model_to_tflite`, it is now the case that every function in the `export_utils` module has been deprecated. Therefore I propose to deprecate the entire module. We can do this using the module `getattr` to emit warnings if a user ever tries to access the two public names (i.e. `export_model` or `export_utils`).
In practice this means import patterns like:
```python
>>> from deepcell.utils import export_model  # or export utils
```
will now raise a deprecation warning as well.
The module `getattr` was added in Python 3.7 - see [PEP 562](https://peps.python.org/pep-0562/) for details.
Further cleanup related to the `export_model` functions, all of which are deprecated in favor of using `tf.keras.models.save_model` directly.

Deprecate entire `export_utils` module

---

README.md

Removing blurb from README about running with Python2/TensorFlow 1.
The chances of this working out of a containerized environment is practically nil and certainly not worth the effort for users.
I'm also using this change as a test for the RTD docs preview feature in CI.

Rm blurb about Python2/TensorFlow 1 from README.

---

requirements.txt
setup.py

* Fix for #655 .
My vote is to pin scikit-image then do a patch release. For the next minor release the pin should be updated to >=0.19.

Pin scikit-image to avoid expired deprecations.

---

.github/workflows/docker-image.yaml
.github/workflows/pypi.yaml
.github/workflows/test-docs.yaml
.github/workflows/tests.yaml

The builtin github actions checkout, setup-python, and cache have all been updated to a later version of node. There are now deprecation warnings for the previous versions in the actions logs.
General maintenance to keep the CI in good shape.
Note there may be other actions that need to be updated, but I'm starting with the main ones so I can see what remains in the logs after these updates.

Bump action versions to avoid deprecation warnings.

---

deepcell/applications/application.py
deepcell/applications/application_test.py

Closes #665. As noted there, the issue arises from pads of `(0, 0)` which subsequently lead to `0:0` slices in untiling, giving arrays with shape 0 for that dimension.
AFAICT, the only way to hit this corner case is when one of the dimensions is smaller than `model_image_shape`, but the other is exactly `model_image_shape`. If both dimensions are `>= model_image_shape`, then `padding` should be `False` if I'm following the logic correctly.
Bugfix

Fix untiling corner-case when no padding in one dimension

---

deepcell/image_generators/cropping.py
deepcell/image_generators/fully_convolutional.py
deepcell/image_generators/sample.py
deepcell/image_generators/scale.py
deepcell/image_generators/semantic.py
deepcell/layers/normalization.py
deepcell/model_zoo/fpn.py
deepcell/model_zoo/panopticnet.py
deepcell/utils/io_utils.py

Ruff v0.278 was released yesterday (07/12) and added pyupgrade checks to use f-strings instead of the str.format method. I'm generally +1 for this, but if there are objections, we could ignore the rule instead.
This PR is the result of `ruff . --fix`
* Fix linting CI and ever-so-slightly modernize the codebase

STY: ruff str.format -> f-strings.

---

deepcell/image_generators/semantic.py
deepcell/utils/transform_utils.py
requirements.txt
setup.py

There have been several deprecations and expirations of deprecations in `scikit-image` as of v0.18 that have affected the codebase. We caught most of these usages in vanvalenlab/deepcell-toolbox#131. Unfortunately, due to internal usage of `functools.wraps`, the stacklevel of some of the calls containing deprecated kwargs had changed, which prevented the DeprecationWarnings from being visible within `deepcell-tf` itself. This leads to all-out failures if scikit-image v0.21 is installed.
This PR fixes the situation by:
- Pinning the lower-bound of scikit-image to 0.19, which is now the minimum version that supports the new keyword argument names. Fixes #670.
- Updating internal usages of scikit-image functions that had relied on kwargs that have now been expired. Fixes #655.
This should …

Fix scikit-image dependency specification

---

requirements.txt
setup.py

Capped Cython in 0.12.1 build reqs to work around issue in deepcell-tf containers.
* Bump `deepcell-toolbox` minimum version
* Fix broken docker containers

MAINT: Require deepcell-toolbox 0.12.1

---

deepcell/_version.py
docs/source/conf.py

* Prepare for 0.12.7 release
* Fix downstream problems related to Cython version used to build deepcell-toolbox

REL: Increment patch version for 0.12.7 release.

---

deepcell/utils/_auth.py

* Fixup for `fetch_data` when a `cachedir` is provided but the parent directory has not yet been created.
* Should make the downloading of assets (i.e. models/datasets) more robust to order and existing directory structure.

Make creation of base download location more robust.

---

deepcell/_version.py
docs/source/conf.py

0.12.9 release - bug fix for authenticated model downloads in fresh directory tree.

REL: bump patch for 0.12.9 release.

---

docs/requirements-docs.txt

@msschwartz21 IIRC the motivation for many of the pins was issues with list rendering in the datasets and applications galleries. They seem to be resolved locally, if you could double-check the dock preview below and confirm these look as expected then I think we're good to go!
* Moving to latest versions of doc deps seems to resolve the issues that motivated the pins in the first place.
* Software maintenance best-practices

Rm pins from doc dependencies.

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml
deepcell/datasets/dynamic_nuclear_net.py
deepcell/datasets/spot_net.py
deepcell/datasets/tissue_net.py
docs/requirements-docs.txt
docs/source/conf.py
pyproject.toml

Some general maintenance to deal with failures cropping up from dependencies either updating or falling out-of-sync with one another
- Force suppression of warnings from `nbsphinx` which break doc tests. Note: nbsphinx breaks sphinx caching (hence the warning)
- Add doc dependencies that nbsphinx needs but are not specified in their deps list
- Modify mocking to fix broken access of numpy features during doc build. This means the docs will no longer build without numpy installed
The newest version of ruff has checks for non-f-string based string formatting. I've silenced these for now - there are much more important issues than string formatting.
- Updated ruff configuration and invocation to match latest release.
* General maintenance, keep CI green

General maintenance to make CI happy

---

deepcell/datasets/spot_net.py
docs/source/datasets/spotnet.py

This PR adds SpotNet version 1.1, which adds Airlocalize to the set of spot detection methods used to create consensus annotations.

Add SpotNet v1.1

---

.github/workflows/tests.yaml
docs/source/applications/caliban.py
pyproject.toml

* #721 modified the interface for model loading to account for the existence of multiple versions. This PR updates the cell tracking gallery example to use the new API.
* Fix (at least a portion) of the docs
* Also replaces deprecated matplotlib API with recommended alternative.
Addresses #728 
--- Additional updates
This PR also includes a couple maintenance updates - namely improvements to the linter configuration and making the docker testing workflow more robust by freeing up virtual diskspace.

DOC: Update application examples with from_version
